server:
  port: 8080
spring:
  application:
    name: pagamentos
  data:
    mongodb:
      host: <host>
      port: <port>
      database: <database>
#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: <endereco>
